- hosts: "{{ deploy_env }}"
  gather_facts: no
  pre_tasks:
    - name: 'Install Python2'
      raw: sudo apt-get update; sudo apt-get -y install python

  vars_prompt:
    - name: "run_init"
      prompt: "Are you deploying to a new server [yes/no]?"
      private: no
    - name: "run_letsencrypt"
      prompt: "Do you want to generate SSL certificate using Let's Encrypt [yes/no]?"
      private: no

  roles:
    - role: common
      when: run_init | bool
    - role: volumes
      when: run_init | bool
    - role: docker
      when: run_init | bool
    - role: aws-cli
      when: run_init | bool
    - role: swarm
    - role: haproxy
      when: run_init | bool
