---
- name: Get aws ecr login
  tags: 'swarm'
  shell: aws ecr get-login --no-include-email --region ap-southeast-2
  register: ecr_get_login

- name: Login to ECR
  tags: 'swarm'
  become: yes
  shell: '{{ ecr_get_login.stdout }}'

- name: Create SWARM directory
  tags: 'swarm'
  become: yes
  file:
    path: "{{ swarm_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'swarm'
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ swarm_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'swarm'
  become: yes
  docker_service:
    project_src: "{{ swarm_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always

- name: Create database init script for SWARM
  tags: 'swarm'
  become: yes
  template:
    src: 0-init-swarm.sql.j2
    dest: "/tmp/0-init-swarm.sql"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: run_init | bool

- name: Init SWARM database
  tags: 'swarm'
  become: yes
  shell: "cat /tmp/0-init-swarm.sql | PGPASSWORD={{ db_password }} psql -U {{ db_user }} -d postgres -h {{ rds_endpoint }}"
  when: run_init | bool

- pause:
    seconds: 10
  when: run_init | bool
    
- name: Restart all containers
  tags: 'swarm'
  become: yes
  docker_service:
    project_src: "{{ swarm_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    restarted: yes
  when: run_init | bool

- name: Create backup script
  tags: 'swarm'
  become: yes
  template:
    src: backup.sh.j2
    dest: "/data/backup.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  when: run_init | bool

- name: Add cron task for backup
  tags: 'swarm'
  become: yes
  cron:
    name: "backup database"
    special_time: "hourly"
    cron_file: "backup"
    user: "root"
    job: "/data/backup.sh"
  when: run_init | bool